<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="Moq" />
      <PackageReference Include="Respawn" />
      <PackageReference Include="Shouldly" />
      <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskTracker.Web\TaskTracker.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="integrationSettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
