FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
COPY .env.docker .env
RUN npm run build

FROM node:22-alpine AS final
WORKDIR /app
COPY --from=build /app/build ./build

EXPOSE 3000
CMD ["npx", "serve", "build", "--listen", "3000", "--single"]
